version: '3'

services:
  open-interpreter:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'open-interpreter'
    container_name: 'open-interpreter'

    volumes:
      - .:/root

    stdin_open: true
    tty: true
#    command: '/bin/bash'